quarkus:
  shutdown:
    timeout: 300
  log:
    category:
      "org.jboss.pnc":
        level: DEBUG
    console:
      format: "%d{HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e mdc:[%X]%n"
    handler:
      kafka:
        enabled: false
        broker-list: kafka.example.com:443
        topic: kafka-topic
        security-protocol: SSL
        ssl-truststore-location: /mnt/kafka-client-truststore.jks
        ssl-truststore-password: none
  oidc:
    auth-server-url: https://keycloak-host/auth/realms/myrealm
    client-id: client
    credentials:
      secret: secret
    tls:
      verification: none
  oidc-client:
    auth-server-url: http://localhost:8180/auth/realms/quarkus/
    client-id: my-app
    credentials:
      secret: secret
repository-driver:
  ignored-path-patterns:
    promotion:
      maven:
      npm:
      generic:
    result:
      maven:
      npm:
      generic:
  ignored-repo-patterns:
  temp-build-promotion-target:
  build-promotion-target:
  self-base-url:
  indy-client:
    api-url:
    request-timeout: 30
  http-client:
    connect-timeout: 5
    request-timeout: 15
  callback-retry-duration: 600
  callback-retry-delay-msec: 500
  callback-retry-max-delay-msec: 5000

"%test":
  quarkus:
    oidc:
      enabled: false
    oidc-client:
      enabled: false
  repository-driver:
    http-client:
      connect-timeout: 1
      request-timeout: 3
    build-promotion-target: "build-target"
    temp-build-promotion-target: "temp-target"
    ignored-path-patterns:
      promotion:
        maven: [".*/maven-metadata\\.xml$", ".*\\.sha1$"]
        npm:
        generic:
      result:
        maven:
        npm:
        generic:
    ignored-repo-patterns: ["maven:.*:ignored", "maven:.+:tobeigno.+"]
    self-base-url: "http://localhost:8081/"
    indy-client:
      api-url: "http://indy-host/api/"
