name: Build snapshot version and upload to Maven Central

on:
  push:
    branches: [ "main" ]

jobs:
    call-snapshot-job:
      uses: project-ncl/shared-github-actions/.github/workflows/maven-snapshot.yml@v0.0.6
      with:
        project_name: 'project-ncl/repository-driver'
      secrets:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
